"""Add link section

Revision ID: 170fb2d21035
Revises: f3d19d137477
Create Date: 2022-05-18 00:53:26.911905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170fb2d21035'
down_revision = 'f3d19d137477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
